```yaml
version: '3.8'

services:
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    networks:
      - dokploy-network
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - dokploy-network

  chronograf:
    image: chronograf:latest
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - KAPACITOR_URL=http://kapacitor:9092
    ports:
      - "8888:8888"
    networks:
      - dokploy-network
    depends_on:
      - influxdb
      - kapacitor

  kapacitor:
    image: kapacitor:latest
    environment:
      - KAPACITOR_HOSTNAME=kapacitor
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    ports:
      - "9092:9092"
    networks:
      - dokploy-network
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    networks:
      - dokploy-network
    env_file:
      - env.grafana
    volumes:
      - ./grafana/etc:/etc/grafana
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - influxdb
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`app.iotwise.com.au`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.grafana.loadbalancer.server.port=3000

  influxdb-cli:
    image: influxdb:latest
    entrypoint:
      - influx
      - -host
      - influxdb
    networks:
      - dokploy-network
    depends_on:
      - influxdb

  kapacitor-cli:
    image: kapacitor:latest
    entrypoint:
      - kapacitor
      - -url
      - http://kapacitor:9092
    networks:
      - dokploy-network
    depends_on:
      - kapacitor

networks:
  dokploy-network:
    driver: bridge
```
