version: '3'

services:
  # Define a Telegraf service
  telegraf:
    image: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    networks:
    - dokploy-network
  # Define an InfluxDB service
  influxdb:
    image: influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - dokploy-network
  # Define a Chronograf service
  chronograf:
    image: chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    networks:
      - dokploy-network

    links:
      - influxdb
      - kapacitor
  # Define a Kapacitor service
  kapacitor:
    image: kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - "9092:9092"
    networks:
      - dokploy-network

  # Define a grafana service
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - dokploy-network

    env_file:
      - 'env.grafana'
    volumes:
      - ./grafana/etc/:/etc/grafana
      - ./grafana/data/:/var/lib/grafana
    links:
      - influxdb

  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
  influxdb-cli:
    image: influxdb
    entrypoint:
      - influx
      - -host
      - influxdb
    links:
      - influxdb
  # Define a service for using the kapacitor CLI tool.
  # docker-compose run kapacitor-cli
  kapacitor-cli:
    image: kapacitor
    entrypoint: bash
    environment:
      KAPACITOR_URL: http://kapacitor:9092
    links:
      - kapacitor

  #Dokploy Settings

  networks: 
    dokploy-network:
      external:true

    labels:
    - traefik.enable=true
    - traefik.http.routers.next-app.rule=Host(`app.iotwise.com.au`)
    - traefik.http.routers.next-app.entrypoints=websecure
    - traefik.http.routers.next-app.tls.certResolver=letsencrypt
    - traefik.http.services.next-app.loadbalancer.server.port=3000

    
    
