
version: "3.8"

services:
  telegraf:
    image: telegraf:latest
    volumes:
      - ..files/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    networks:
      - dokploy-network
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    volumes:
      - ..files/influxdb/data:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - dokploy-network

  chronograf:
    image: chronograf:latest
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - KAPACITOR_URL=http://kapacitor:9092
    ports:
      - "8888:8888"
    networks:
      - dokploy-network
    depends_on:
      - influxdb
      - kapacitor
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.chronograf.rule=Host(`chronograf.iotwise.com.au`)
      - traefik.http.routers.chronograf.entrypoints=websecure
      - traefik.http.routers.chronograf.tls.certresolver=letsencrypt
      - traefik.http.services.chronograf.loadbalancer.server.port=8888
      - traefik.enable=true

  kapacitor:
    image: kapacitor:latest
    environment:
      - KAPACITOR_HOSTNAME=kapacitor
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    ports:
      - "9092:9092"
    networks:
      - dokploy-network
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    networks:
      - dokploy-network
    env_file:
      - env.grafana
    volumes:
      - ..files/grafana/etc:/etc/grafana
      - ..files/grafana/data:/var/lib/grafana
    depends_on:
      - influxdb
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.grafana.rule=Host(`app.iotwise.com.au`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.enable=true

  influxdb-cli:
    image: influxdb:latest
    entrypoint:
      - influx
      - -host
      - influxdb
    networks:
      - dokploy-network
    depends_on:
      - influxdb

  kapacitor-cli:
    image: kapacitor:latest
    entrypoint:
      - kapacitor
      - -url
      - http://kapacitor:9092
    networks:
      - dokploy-network
    depends_on:
      - kapacitor

  traefik:
    image: traefik:latest
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email= info@iwebx.com.au"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "8080:80" # For HTTP-01 challenge
      - "8443:443" # For HTTPS, avoiding 443 conflict
    volumes:
      - ..files/var/run/docker.sock:/var/run/docker.sock:ro
      - ..files/letsencrypt:/letsencrypt
    networks:
      - dokploy-network

networks:
  dokploy-network:
    driver: overlay
